### ISSUE TITLE
Analyse impact of EBM guide sept 2020 and implement changes

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/measuringoutcome#12]
Most specifically, KVM's that have been updated or changed, also the 'table' with KVM's at the end of the deck!

**Done 03-01-2021:** 

- Updated the seperate PPT with wording changes in the KVA descriptions 
- KVM wording changes (and split of one kvm to two)
- removal of Feature usage index.
- adding new KVMs (most from DORA 2019 report)
- Total Green cards 17, total purple cards 17 (from green 10, purple 13).
- Updated version number to v2
- Added 'Based on 2020 EBM Guide.' to credits section

See below comments for more details.

**Comment by sjoerdly** [comment]
[EBM Guide 2020_1.pdf](https://github.com/ScrumFacilitators/measuringoutcome-en/files/5383332/EBM.Guide.2020_1.pdf)

**Comment by ctonylee** [comment]
I am working on the [Traditional Chinese (CHT) version](https://github.com/ScrumFacilitators/measuringoutcome-cht) and found the following KVM changes.

Hope this sharing helps saving others some time.

Color code on the image:
* Orange = changed the wording, splitter into two records
* Green = new KVM
* Red = no longer observed


![image](https://user-images.githubusercontent.com/1815759/102305307-a030d380-3f9a-11eb-8320-2be52f0378c8.png)

**Comment by sjoerdly** [comment]
Updated the seperate PPT with wording changes in the KVA descriptions and KVM wording changes and the removal of Feature usage index. 

TODO: add new KVM's and update the overview cheat sheet.

**Comment by sjoerdly** [comment]
- [x] Desired Customer Experience or satisfaction
- [x] Lead Time for Changes 
- [x] Deployment Frequency 
- [x] Time to Restore Service
- [x] Time to remove Impediment
- [x] Time to Pivot
- [x] Change Failure Rate

Side note: most of these new additions come from the 2019 DORA report https://research.google/pubs/pub48455/

**Comment by sjoerdly** [comment]
Asked @cheehonghsia to review. If no issues found, rename file (effectively removing old 2019 version) and create new release.

**Comment by sjoerdly** [comment]
No issues found!
