### ISSUE TITLE
Add translations to maximize impact for non-english regions

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/measuringoutcome#2]
Since Scrum Facilitators is a global movement, for some facilitators it may be better suited to have local translations to maximize impact.

Some languages that may be good to start with:

- [x] Spanish (see [Measuring Outcomes (espanol)](https://github.com/ScrumFacilitators/measuringoutcome-es)  repo)
- [x] Dutch
- Chinese
- German
- Pirate

Please add ideas and motivations for additional languages in the comments below. Even better: create your local translation and create a pull request if you're ready.

Side note 1: we should keep an eye on translations of the EBM guide and make sure translations of the KVA's & KVM's are in sync.

Side note 2: It may be enough for a first start to just translate the instructions and leave the KVA/KVM's in english as the [EBM guide](https://www.scrum.org/resources/evidence-based-management-guide) is only (currently) officially available in english (and russian).

**Comment by natastro** [comment]
Would love to help with Spanish translations if needed! Thank you!
Have a great weekend :)

**Comment by sjoerdly** [comment]
@stroudn1 awesome! How would you like to approach this? 

I can already see value in a small increment of just having the descriptions and introduction in spanish. For the KVA/KVMs (EBM material) it may be useful to keep them english as they form a framework. 

In a second step we could contemplate also translating them, or adding the explanations in spanish as an extra cheat sheet? 

Anyway I will 'refine' a separate issue for the first translation work and assign it to you. Feel free to pick it up any way you see fit. There is no time pressure and I am not sure how big the 'customer' need is. Any insights in that direction are welcome too!

**Comment by natastro** [comment]
Hi @sjoerdly ! Just want to clarify, will translations only apply to what's under 'measuringoutcome' or anything under ScrumFacilitators? I know in doing translations on GitHub it differs but a lot of times groups have an 'en' repository and then an 'es' repository and whatever is 'en' is translated (if that makes sense). May I also have guidance as far as what/where the KVA/KVMs (EBM material) are?

**Comment by sjoerdly** [comment]
Hi @stroudn1 good questions. I guess it is possible to have more of the materials translated. It’s about demand also ofcourse. 

I like your suggested setup with en/es/<etc> repos. 

That seems a bit cleaner than keeping it all in one. Lemme sleep on it and see what the others think. I think we will end up following your experience here :-)

**Comment by sjoerdly** [comment]
About what are kva/kvm’s: the main cards are kva’s (time to market, ability to innovate, etc). Those have the orange border. 

The kvm’s are the cards with a blue background (lead time, customer satisfaction, etc). Those are also listed in the ‘cheat sheet’ on one of the last cards.

I hope this clarifies. But if you like, I could create a powerpoint with comments as to what I think should be translated in the first run?

Also insight into needs of the target community are welcome. Does it even make sense to leave the kva & kvm in english?

**Comment by natastro** [comment]
Thank you for the clarification @sjoerdly - I should be able to get an idea of where to start!

I'm happy to translate as much or as little needed. If it's any help - I know there are certain things that are kept as English in the Spanish language. So for example - 'ScrumFacilitators' is a name that would be kept in English. Same thing when you think about English movie titles or book titles, so on. 

I'll take a look at everything soon and get started! :) Thank you for letting me help!

**Comment by sjoerdly** [comment]
dutch repo initiated https://github.com/ScrumFacilitators/measuringoutcome-nl

**Comment by sjoerdly** [comment]
Both spanish and dutch were released. Closing this issue for now as we are creating seperate repo's per translation.
